name: ☕ </> Code Brewing Notes
url: http://jwsong.github.io
description: Notes on software development

permalink: /:year/:month/:day/:title/
paginate: 10

plugins:
  - jekyll-paginate

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
