# Deploy static website to `gh-pages` branch
name: pages-build

# Triggers for the workflow to run
on:
  push:
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Jobs to run on trigger
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      
      # Checkout the repository
      - uses: actions/checkout@v2

      # Cache dependencies and build outputs
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Build static website
      - uses: helaili/jekyll-action@v2
        with:
          target_branch: 'gh-pages'
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_build_commands: apk --update add graphviz
